CREATE TABLE `sip_buddies` (
 `id` int(11) NOT NULL auto_increment,
 `name` varchar(80) NOT NULL,
 `callerid` varchar(80) default NULL,
 `defaultuser` varchar(80) NOT NULL,
 `regexten` varchar(80) NOT NULL,
 `secret` varchar(80) default NULL,
 `mailbox` varchar(50) default NULL,
 `accountcode` varchar(20) default NULL,
 `context` varchar(80) default NULL,
 `amaflags` varchar(7) default NULL,
 `callgroup` varchar(10) default NULL,
 `canreinvite` char(3) default 'yes',
 `defaultip` varchar(15) default NULL,
 `dtmfmode` varchar(7) default NULL,
 `fromuser` varchar(80) default NULL,
 `fromdomain` varchar(80) default NULL,
 `fullcontact` varchar(80) default NULL,
 `host` varchar(31) NOT NULL,
 `insecure` varchar(4) default NULL,
 `language` char(2) default NULL,
 `md5secret` varchar(80) default NULL,
 `nat` varchar(5) NOT NULL default 'no',
 `deny` varchar(95) default NULL,
 `permit` varchar(95) default NULL,
 `mask` varchar(95) default NULL,
 `pickupgroup` varchar(10) default NULL,
 `port` varchar(5) NOT NULL,
 `qualify` char(3) default NULL,
 `restrictcid` char(1) default NULL,
 `rtptimeout` char(3) default NULL,
 `rtpholdtimeout` char(3) default NULL,
 `type` varchar(6) NOT NULL default 'friend',
 `disallow` varchar(100) default 'all',
 `allow` varchar(100) default 'g729;ilbc;gsm;ulaw;alaw',
 `musiconhold` varchar(100) default NULL,
 `regseconds` int(11) NOT NULL default '0',
 `ipaddr` varchar(15) NOT NULL,
 `cancallforward` char(3) default 'yes',
 `lastms` int(11) NOT NULL,
 `useragent` char(255) default NULL,
 `regserver` varchar(100) default NULL,
 PRIMARY KEY  (`id`),
 UNIQUE KEY `name` (`name`),
 KEY `name_2` (`name`)
 ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
